### ISSUE TITLE
Change Method of DB Access

### ISSUE THREAD

**Issue by mcdonnnj** [mzack5020/findings-data-import#2]
Your current function does not allow credentialed access to a MongoDB server. I would suggest either adding more parameters, or alternatively switching to using Parameter Store and retrieving them using the [SSM service](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html). The Parameter Store is how we currently store MongoDB credentials for our other deployments. You have also hardcoded the database to use which runs counter to the setup of your function.

**Comment by mzack5020** [comment]
Ok I will look into this. Thanks!

**Comment by mzack5020** [comment]
Code is now changed to use the SSM service. Thanks for the recommendation!

**Comment by mcdonnnj** [comment]
Nice. Thanks for adding that functionality.
