### ISSUE TITLE
Unused Command Line Options

### ISSUE THREAD

**Issue by mcdonnnj** [mzack5020/findings-data-import#3]
I do not see you use `--starts-with`, `--contains`, or `--ends-with` anywhere. If they are no longer being used they should be removed from the docopt declaration.

**Comment by mzack5020** [comment]
These are used in lambda_handler, lines 69-72

**Comment by mcdonnnj** [comment]
Right, they are used as environment values in the handler. They are never used in code from `findings_data_import.py` which is where you have them as command line options.

**Comment by mzack5020** [comment]
These command line arguments were removed. Thanks!

**Comment by mcdonnnj** [comment]
Thanks.
