### ISSUE TITLE
Possible Unnecessary Uses of F-Strings

### ISSUE THREAD

**Issue by mcdonnnj** [mzack5020/findings-data-import#4]
You use f-strings in multiple places: 153, 161, 166, 167, 299, 300 where it seems unnecessary. Then in some places like 256-264 and 276-284 you do not but they seem like good places to use them.

Edited to reflect line changes from other issues being resolved.

**Comment by mzack5020** [comment]
I did my best trying to match up the line numbers with your issue since some of them have shifted but I think I got all of them.

**Comment by mcdonnnj** [comment]
Nice, thanks. 👍
